### ISSUE TITLE
Widgets button

### ISSUE THREAD

**Issue by abbycabs** [WormBase/website-mobile#14]
Can you move it above the yellow bar?

Also, keep it in the menu bar on top

**Comment by Kevin-Mohamed** [comment]
Alright, can you look here now: http://dev.wormbase.org:9003/#object/protein/A02773

**Comment by abbycabs** [comment]
Thanks @Kevin-Mohamed - this looks good.

Do people think it might be clearer if we added an 'Add more widgets' button at the bottom of the page? Especially if the menu isn't fixed anymore?

What do you and @sibyl229 think?

**Comment by Kevin-Mohamed** [comment]
I agree, I think it looks better - look (what do u think):
http://dev.wormbase.org:9003/#object/protein/A02773

**Comment by sibyl229** [comment]
I think so too. Also the user doesn't have to go back to the top to press
the widget button.

Sibyl

**Comment by abbycabs** [comment]
Thanks, I like it.

@Kevin-Mohamed - feel free to push your changes here and close the issue.
