### ISSUE TITLE
Link to report bugs

### ISSUE THREAD

**Issue by abbycabs** [WormBase/website-mobile#15]
Add a link to the side bar to: 
http://www.wormbase.org/tools/support

**Comment by abbycabs** [comment]
Hey @sibyl229 - could you look at this issue? We just need a way for users to report bugs from the mobile site and linking to our main site seemed easiest.

Comment here if you have any questions or suggestions! @Kevin-Mohamed and I will be around. We plan on releasing tomorrow.

**Comment by sibyl229** [comment]
Hi @acabunoc Sure. I try the way you suggest for this release. 
After this release, maybe we can try something sophisticated like creating a mobile page for it. Or the free plan of UserVoice (not sure whether that would be harder or easier to implement).

**Comment by abbycabs** [comment]
Thanks @sibyl229 - yes, something at least mobile would be better. Future.
