### ISSUE TITLE
'Report bug' -> 'Contact help'

### ISSUE THREAD

**Issue by abbycabs** [WormBase/website-mobile#17]
From a comment here:

https://github.com/WormBase/website-mobile/pull/16#commitcomment-6095965

Can we change 'Report bug' to 'Contact help'?

**Comment by sibyl229** [comment]
Hi @acabunoc I will change this right away. I forgot to ask yesterday. Is there some other issue for me today?

**Comment by abbycabs** [comment]
Thanks @sibyl229! I might make a couple more issues soon - feel free to take a look!

**Comment by sibyl229** [comment]
@acabunoc No problem! I will send a pull request after fixing a few more issues.
