### ISSUE TITLE
please change "Processes" and "wbprocess" 

### ISSUE THREAD

**Issue by kyook** [WormBase/website-mobile#3]
"Process" and "wbprocess"  to "Topics"

**Comment by Kevin-Mohamed** [comment]
@kyook 
Hello, I am now working on the mobile site for wormbase,
can you fill me in on what do you mean here - is this just a text change somewhere? (maybe you could send me an example?)

**Comment by kyook** [comment]
Hi Kevin,

Yes, these are just webpage text changes.  The attached screen shots should
show you what I mean (I hope) - that in place of the term "Process" use
"Topic".

Best,
Karen

On Wed, Mar 26, 2014 at 12:57 PM, Kevin Mohamed notifications@github.comwrote:

> @kyook https://github.com/kyook
> Hello, I am now working on the mobile site for wormbase,
> can you fill me in on what do you mean here - is this just a text change
> somewhere? (maybe you could send me an example?)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-38731807
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by Kevin-Mohamed** [comment]
did you forget to attach them?

**Comment by kyook** [comment]
Sorry I had replied through e-mail with the attachments rather than through git hub itself.

![screen shot 2014-03-26 at 2 06 00 pm](https://cloud.githubusercontent.com/assets/611610/2532040/880bdab2-b53a-11e3-89f9-dc5f37eb41fd.png)

![screen shot 2014-03-26 at 2 05 14 pm](https://cloud.githubusercontent.com/assets/611610/2532042/8a44ecba-b53a-11e3-8194-9afe5be4f2ff.png)

**Comment by Kevin-Mohamed** [comment]
Hello,
Sorry, still a little confused, I already see the word "Topics" there, I don't see processes - 
 you mean the link that it leads to (so change the instances of wbprocess), correct? http://dev.wormbase.org:8082/#resources/wbprocess

**Comment by kyook** [comment]
Hi Kevin,

Yes, the change from Process to Topic already occurred on the website.  The
mobile site should reflect the same use of the term Topics as they appear
in the images.

Love the mobile site!

I'm confused about the need to have 'wbprocess' underneath the topic term
in your example.   If you need to display a class name akin to 'Gene' or
'Variation' then yes, if you can please use 'Topic' instead of wbprocess.
Unfortunately the class name is WBProcess, so I don't know if you can, or
how easy it is to alter the display name.

Sorry for the confusion.
Feel free to skype of google chat me.  Skype name : wbkaren

Karen

On Mon, Mar 31, 2014 at 9:04 AM, Kevin Mohamed notifications@github.comwrote:

> Hello,
> Sorry, still a little confused, I already see the word "Topics" there, I
> don't see processes -
> you mean the link that it leads to (so change the instances of wbprocess),
> correct? http://dev.wormbase.org:8082/#resources/wbprocess
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-39106550
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by Kevin-Mohamed** [comment]
@kyook 
Can u look at it now from here:
http://dev.wormbase.org:9003

**Comment by kyook** [comment]
Works fine on my desktop. On my mobile it takes too long to load and crashes. Abby was working with it when I was there. Perhaps she'll have some insight for you?

-mobile-

**Comment by Kevin-Mohamed** [comment]
@kyook are you referring to loading app or just the wbprocess/topics page (problem of the task(

**Comment by kyook** [comment]
Hi Kevin,

I can't access the app on my phone, it crashes after trying to load.

On the web, I can get to the topic browser.  Clicking on Aging does take me
to the aging page, where only the Overview widget is displayed. Is this how
it should be working?

Karen

On Wed, Apr 16, 2014 at 10:19 AM, Kevin Mohamed notifications@github.comwrote:

> @kyookhttps://github.com/kyook?utm_campaign=website&utm_source=sendgrid.com&utm_medium=emailare you referring to loading app or just the wbprocess/topics page (problem
> of the task(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email#issuecomment-40626470
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by Kevin-Mohamed** [comment]
@kyook 
what are you using?

**Comment by kyook** [comment]
for the web, I am using Firefox.

On Wed, Apr 16, 2014 at 10:33 AM, Kevin Mohamed notifications@github.comwrote:

> @kyook https://github.com/kyook
> what are you using?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-40628044
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by kyook** [comment]
Just checked on Chrome, also only got the Overview widget.

On Wed, Apr 16, 2014 at 11:06 AM, Karen Yook kyook@wormbase.org wrote:

> for the web, I am using Firefox.
> 
> On Wed, Apr 16, 2014 at 10:33 AM, Kevin Mohamed notifications@github.comwrote:
> 
> > @kyook https://github.com/kyook
> > what are you using?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-40628044
> > .
> 
> ## 
> 
> ```
> Karen Yook
> 
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren
> 
> 
> 
> ```

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by Kevin-Mohamed** [comment]
@kyook 

sorry, just confirmation - you know you can alter which widgets are showing right?

I was thinking maybe that's not intuitive enough

Also, I meant which one for the phone (like iOS or Android?)

**Comment by kyook** [comment]
Hi Kevin,

Oh, I didn't see the widget control, sorry.

I have an iPhone 5S updated to version 7.1.  Abby can tell you more about
what she did to get it to work.  She needed to install google chrome on my
phone. When I open it there, it works, although it is pretty glitchy trying
to move from screen to screen.  That is I can get to the topic page no
problem, I can select the widget control and select a new widget, but then
I can't get back to the topic page to see it, scrolling down the page is a
bit tricky as the side menu keeps moving the page out of view. It would get
stuck, but then resolve.  Perhaps it is glitchy because you are working on
it.

On Wed, Apr 16, 2014 at 11:48 AM, Kevin Mohamed notifications@github.comwrote:

> @kyook https://github.com/kyook
> 
> sorry, just confirmation - you know you can alter which widgets are
> showing right?
> 
> I was thinking maybe that's not intuitive enough
> 
> Also, I meant which one for the phone (like iOS or Android?)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-40636898
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```

**Comment by abbycabs** [comment]
The wbprocess  to topic problem seems to resolved. Closing

There are several other issues open on the other bugs you've described, @kyook 
#4 #1

**Comment by kyook** [comment]
Thanks Abby.
Karen

On Mon, Apr 21, 2014 at 12:27 PM, Abigail Cabunoc
notifications@github.comwrote:

> The wbprocess to topic problem seems to resolved. Closing
> 
> There are several other issues open on the other bugs you've described,
> @kyook https://github.com/kyook
> #4 https://github.com/WormBase/website-mobile/issues/4 #1https://github.com/WormBase/website-mobile/issues/1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WormBase/website-mobile/issues/3#issuecomment-40967424
> .

## 

```
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
```
