### ISSUE TITLE
keeps crashing on iOS 6.1.3

### ISSUE THREAD

**Issue by kyook** [WormBase/website-mobile#4]
is the app compatible with a specific iOS?

**Comment by kyook** [comment]
I should say, I can access it, but when I try to Search for something, it spins and then the app closes.

**Comment by draciti** [comment]
I copy that with iOS version 7.0.3

**Comment by Kevin-Mohamed** [comment]
@kyook 
Hello,
do you think you could try again (it works for iOS 5.1.1) - before I ask for access to a new version I want to make sure this problem is still there (maybe someone fixed it since)
