### ISSUE TITLE
protein page buglets

### ISSUE THREAD

**Issue by epaule** [WormBase/website-mobile#5]
http://m.wormbase.org/#object/protein/BM:BM27029

doesn't show the protein motif picture or the "full blastp" thingy.

**Comment by Kevin-Mohamed** [comment]
@epaule 
Can you please view the changes here:
http://dev.wormbase.org:9003/#object/protein/BM:BM27029

**Comment by epaule** [comment]
nope, I get a:
Error code: ERR_CONNECTION_REFUSED

**Comment by Kevin-Mohamed** [comment]
@epaule 
Sorry, check again (the server was down)

**Comment by epaule** [comment]
Works now.
But I think the small image for the protein motifs (the one with the round bars for motifs) we use on the live site would look better than the bioperl/gbrowse one.

Also the "best human ortholog" is not the best human ortholog, but the best human blast hit/homolog (the ortholog would be in the ortholog section).
